replicaCount: 1

image:
  repository: 444896211196.dkr.ecr.us-east-2.amazonaws.com/hello-world-app
  tag: "6bffadff7e99ea486a31f5648d3d3d2b31f4c5a7"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 32Mi

autoscaling:
  enabled: false

  minReplicas: 1
  maxReplicas: 12
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50