replicaCount: 1

image:
  repository: 444896211196.dkr.ecr.us-east-2.amazonaws.com/hello-world-app
  tag: "dca3ede5c07f100c36fb80b0c365e71d9e56f485"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 32Mi

autoscaling:
  enabled: false

  minReplicas: 1
  maxReplicas: 12
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50