replicaCount: 1

image:
  repository: 444896211196.dkr.ecr.us-east-2.amazonaws.com/hello-world-app
  tag: "8e69494453d45ae6c726fb9658c8ad54b140cc67"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 12
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50